import pygame
# Screen stuff
FPS = 30
SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
SCREEN_SIZE = SCREEN_WIDTH, SCREEN_HEIGHT

# color stuff
BLACK = 0,0,0
WHITE = 255,255,255
BLUE = 0,0,255

# font stuff
BASICFONTSIZE = 16
pygame.init()
BASICFONT = pygame.font.Font(None, BASICFONTSIZE)


# debug
DEBUG = True
# DEBUG = False


# player stuff
BASE_HEALTH = 16
GRAVITY = 2
JUMP_SPEED = 22
RUN_SPEED = 10
DASH_MULT = 2
DASH_TIME = 10
WALL_JUMP_VELOCITY_HOLD = 3
WALL_DRAG_SPEED = 6

DASH_ECHOS = 3
