import pygame
# Screen stuff
FPS = 30
SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
SCREEN_SIZE = SCREEN_WIDTH, SCREEN_HEIGHT
SCREEN_ASPECTRATIO = float(SCREEN_WIDTH)/float(SCREEN_HEIGHT)

SCREEN_HREZ = int(864/1.5)
SCREEN_VREZ = int(486/1.5)
SCREEN_REZ = SCREEN_HREZ, SCREEN_VREZ

# color stuff
BLACK = 0,0,0
WHITE = 255,255,255
RED = 255,0,0
GREEN = 0,255,0
BLUE = 0,0,255
YELLOW = 255,255,0
CYAN = 0,255,255
MAGENTA = 255,0,255

COLOR_DICT = {
              'BLACK': BLACK,
              'WHITE': WHITE,
              'RED': RED,
              'GREEN': GREEN,
              'BLUE': BLUE,
              'YELLOW': YELLOW,
              'CYAN': CYAN,
              'MAGENTA': MAGENTA,
             }


# font stuff
BASICFONTSIZE = 16
pygame.init()
BASICFONT = pygame.font.Font(None, BASICFONTSIZE)


# debug
# DEBUG = True
DEBUG = False


# player stuff
BASE_HEALTH = 16
GRAVITY = 2
JUMP_SPEED = 22
RUN_SPEED = 10
DASH_MULT = 2
DASH_TIME = 10
WALL_JUMP_VELOCITY_HOLD = 3
WALL_DRAG_SPEED = 6
MAX_SHOTS = 3
STAGGER_VELOCITY = 5

X_STANDING_HITBOX_W = 20
X_STANDING_HITBOX_H = 42

DASH_ECHOS = 3


# level stuff
LEVEL_TILE_SIZE = 40


# server and network stuff

DEFAULT_SERVER_IP = "127.0.0.1"
DEFAULT_SERVER_PORT = 12000
